eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000

spring:
  appliation:
    name: gateway
  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: path_route
          uri: lb://PERSON-API
          predicates:
            - Path=/api/v1/people
            
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*" # Habilita vários paths para check status do servidor
#spring.cloud.gateway.routes.id=person-api
#spring.cloud.gateway.routes.uri=http://localhost:8081/api/v1/device
#spring.cloud.gateway.routes.predicates=Path=/device/**
