eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring: 
  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes: 
        - id: person-api
          uri: http://localhost:8081/api/v1/people
          predicates:
            - Path=/people/**
#spring.cloud.gateway.routes.id=person-api
#spring.cloud.gateway.routes.uri=http://localhost:8081/api/v1/device
#spring.cloud.gateway.routes.predicates=Path=/device/**
